### PR TITLE
Adding cli user and password options

### LINKED ISSUE #599: Add Jenkins 2.54 new cli options: -http, -ssh, -remoting  to jenkins_script resource
### Cookbook version

4.2.1

### Chef-client version

Chef Development Kit Version: 1.2.22
chef-client version: 12.18.31
delivery version: master (0b746cafed65a9ea1a79de3cc546e7922de9187c)
berks version: 5.6.1
kitchen version: 1.15.0

### Platform Details

workstation - OS-X 10.12.4
target - Ubuntu 16.04 on EC2

### Scenario:
I would like to execute my groovy scripts on Jenkins 2.54 as before. So, want to add the '-remoting' flag to the jenkins_script resource.

### Steps to Reproduce:

Running jenkins_script resource

### Actual Result:

Works like a charm for Jenkins 2.53 and bellow
Works for Jenkins 2.54 when executing manually with the '-remoting' flag.
For Jenkins 2.54 with jenkins_script resource:

ec2-54-76-216-204.eu-west-1.compute.amazonaws.com [0m    ---- Begin output of "java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8080 groovy /tmp/groovy20170414-1437-11rb2yt ----
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com [0m    STDOUT: 
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com [0m    STDERR: ERROR: This command is requesting the deprecated -remoting mode. See https://jenkins.io/redirect/cli-command-requires-channel
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com [0m    ---- End output of "java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8080 groovy /tmp/groovy20170414-1437-11rb2yt ----
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com [0m    Ran "java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8080 groovy /tmp/groovy20170414-1437-11rb2yt returned 5[0m

### PR DESCRIPTION
**Pull request by ddegoede**
### Description

This adds a specified user to use for basic authentication for the jenkins-cli
using a username and password, where the password is a token

Signed-off-by: Daan de Goede <ddegoede@schubergphilis.com>

### Issues Resolved

This partially fixes #599, is enables http protocol if a username and password is given. 

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by Xorima** [comment]
Hey @ddegoede 

Can you add a changelog entry for me so we can look to get this shipped?

Thanks!

**Comment by ddegoede** [comment]
Hi @Xorima will do so tomorrow. Thanks for checking this PR.

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ddegoede** [comment]
Hi @Xorima, I added/amended the changelog, hope you do not mind me taking credit for the groovy indentation fix, merged earlier. Also rebased and fixed the spec test.

**Review by Xorima — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [8.1.0](https://github.com/sous-chefs/jenkins/releases/tag/8.1.0)

**Comment by ddegoede** [comment]
@Xorima that was quick 👍 I was just reading this page about the cli and authentication, and saw that it is actually the apitoken and not a password, shall I create a next MR to reflect this? And also add the option to use file based authentication for the `-auth` option?

**Comment by Xorima** [comment]
> @Xorima that was quick 👍 I was just reading this [page](https://www.jenkins.io/doc/book/managing/cli/) about the cli and authentication, and saw that it is actually the apitoken and not a password, shall I create a next MR to reflect this? And also add the option to use file based authentication for the `-auth` option?


Yes please, I'm not a Jenkins expert by any means btw, I just merge stuff (releases are automated here)

Would you be willing to help maintain this cookbook as it sounds like you have a lot more knowledge than I do on Jenkins?

**Comment by nuclearsandwich** [comment]
> Would you be willing to help maintain this cookbook as it sounds like you have a lot more knowledge than I do on Jenkins?

I'm happy to help review changes as well. Open Robotics is using this jenkins cookbook for several different large Jenkins instances and while our job configurations are all done outside of chef cutting away at the manual steps in bootstrapping and updating our global Jenkins configuration is a situation we're actively trying to improve.

**Comment by Xorima** [comment]
For anyone willing to help maintain drop by #sous-chefs on chef community slack and we can walk you through the process of joining the org :)

**Pull request merged**
