### PR TITLE
jenkins_user bugfix: If user has more than one public key it tries to…

### PR DESCRIPTION
**Pull request by alexandrezia**
… create/update the user on each run, it's not comparing publick_keys correctly to be idempotent

### CODE REVIEW

**Comment by Xorima** [comment]
Hey @alexandrezia 

Can you add an entry to the changelog so we can get this shipped please?

Thanks

**Comment by ramereth** [comment]
@alexandrezia can you please rebase and then add a changelog?

**Comment by alexandrezia** [comment]
Sorry, I don't have context about this anymore, it was too long ago ...

**Review by ramereth — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [8.2.1](https://github.com/sous-chefs/jenkins/releases/tag/8.2.1)

**Pull request merged**
