### PR TITLE
Cleanup changelog formatting

### PR DESCRIPTION
**Pull request by nuclearsandwich**
# Description

Update changelog formatting to meet standards and pass markdown-link-check.

Links to tickets.chef.io no longer resolve, causing failures in the markdown-link-check linter.
I have removed those links but preserved the bug numbers in case there's an archive of those floating around somewhere.

I also updated some recent changelog entries which were created by automation to use the bullet-list markdown formatting preferred for changelog entries.

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
  - The changes here are meta and I don't think they merit their own changelog entry
- ~~New functionality includes testing.~~
  - No new functionality has been added.
- ~~New functionality has been documented in the README if applicable.~~
  - No new functionality has been added.

### CODE REVIEW

**Comment by ramereth** [comment]
@nuclearsandwich don't forget to actually add an entry under unreleased for this PR

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich don't forget to actually add an entry under unreleased for this PR

I had written in the PR description that since the changes were "meta" and minor I didn't think they merited a changelog entry. But I don't feel strongly about it if you think I should add one.

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich without a new entry in the changelog under _unreleased_ there won't be a new entry under the new release. Which will funnily enough make the changelog look ugly again laughing

Thanks for the context. I can't quite bring myself to say "makes sense" but I understand. Entry added in [c1788d3](https://github.com/sous-chefs/jenkins/pull/809/commits/c1788d361639e34e8ac076085f2780b34dbdf305)

**Comment by kitchen-porter** [comment]
Released as: [9.5.16](https://github.com/sous-chefs/jenkins/releases/tag/9.5.16)

**Pull request merged**
